# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ykiryanov/Public/webrtcsays.ai/src/modules/third_party/whillats

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ykiryanov/Public/webrtcsays.ai/src/modules/third_party/whillats

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/opt/homebrew/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/opt/homebrew/bin/cpack --config ./CPackSourceConfig.cmake /Users/ykiryanov/Public/webrtcsays.ai/src/modules/third_party/whillats/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ykiryanov/Public/webrtcsays.ai/src/modules/third_party/whillats/CMakeFiles /Users/ykiryanov/Public/webrtcsays.ai/src/modules/third_party/whillats//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ykiryanov/Public/webrtcsays.ai/src/modules/third_party/whillats/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pcaudiolib_external

# Build rule for target.
pcaudiolib_external: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pcaudiolib_external
.PHONY : pcaudiolib_external

# fast build rule for target.
pcaudiolib_external/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcaudiolib_external.dir/build.make CMakeFiles/pcaudiolib_external.dir/build
.PHONY : pcaudiolib_external/fast

#=============================================================================
# Target rules for targets named copy_espeak_data

# Build rule for target.
copy_espeak_data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copy_espeak_data
.PHONY : copy_espeak_data

# fast build rule for target.
copy_espeak_data/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copy_espeak_data.dir/build.make CMakeFiles/copy_espeak_data.dir/build
.PHONY : copy_espeak_data/fast

#=============================================================================
# Target rules for targets named llava

# Build rule for target.
llava: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llava
.PHONY : llava

# fast build rule for target.
llava/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llava.dir/build.make CMakeFiles/llava.dir/build
.PHONY : llava/fast

#=============================================================================
# Target rules for targets named llava_shared

# Build rule for target.
llava_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llava_shared
.PHONY : llava_shared

# fast build rule for target.
llava_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llava_shared.dir/build.make CMakeFiles/llava_shared.dir/build
.PHONY : llava_shared/fast

#=============================================================================
# Target rules for targets named whillats

# Build rule for target.
whillats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whillats
.PHONY : whillats

# fast build rule for target.
whillats/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/build
.PHONY : whillats/fast

#=============================================================================
# Target rules for targets named test_whillats

# Build rule for target.
test_whillats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_whillats
.PHONY : test_whillats

# fast build rule for target.
test_whillats/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_whillats.dir/build.make CMakeFiles/test_whillats.dir/build
.PHONY : test_whillats/fast

#=============================================================================
# Target rules for targets named ggml-base

# Build rule for target.
ggml-base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-base
.PHONY : ggml-base

# fast build rule for target.
ggml-base/fast:
	$(MAKE) $(MAKESILENT) -f _deps/whisper-build/ggml/src/CMakeFiles/ggml-base.dir/build.make _deps/whisper-build/ggml/src/CMakeFiles/ggml-base.dir/build
.PHONY : ggml-base/fast

#=============================================================================
# Target rules for targets named ggml

# Build rule for target.
ggml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml
.PHONY : ggml

# fast build rule for target.
ggml/fast:
	$(MAKE) $(MAKESILENT) -f _deps/whisper-build/ggml/src/CMakeFiles/ggml.dir/build.make _deps/whisper-build/ggml/src/CMakeFiles/ggml.dir/build
.PHONY : ggml/fast

#=============================================================================
# Target rules for targets named ggml-cpu

# Build rule for target.
ggml-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-cpu
.PHONY : ggml-cpu

# fast build rule for target.
ggml-cpu/fast:
	$(MAKE) $(MAKESILENT) -f _deps/whisper-build/ggml/src/CMakeFiles/ggml-cpu.dir/build.make _deps/whisper-build/ggml/src/CMakeFiles/ggml-cpu.dir/build
.PHONY : ggml-cpu/fast

#=============================================================================
# Target rules for targets named ggml-blas

# Build rule for target.
ggml-blas: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-blas
.PHONY : ggml-blas

# fast build rule for target.
ggml-blas/fast:
	$(MAKE) $(MAKESILENT) -f _deps/whisper-build/ggml/src/ggml-blas/CMakeFiles/ggml-blas.dir/build.make _deps/whisper-build/ggml/src/ggml-blas/CMakeFiles/ggml-blas.dir/build
.PHONY : ggml-blas/fast

#=============================================================================
# Target rules for targets named ggml-metal

# Build rule for target.
ggml-metal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-metal
.PHONY : ggml-metal

# fast build rule for target.
ggml-metal/fast:
	$(MAKE) $(MAKESILENT) -f _deps/whisper-build/ggml/src/ggml-metal/CMakeFiles/ggml-metal.dir/build.make _deps/whisper-build/ggml/src/ggml-metal/CMakeFiles/ggml-metal.dir/build
.PHONY : ggml-metal/fast

#=============================================================================
# Target rules for targets named whisper

# Build rule for target.
whisper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper
.PHONY : whisper

# fast build rule for target.
whisper/fast:
	$(MAKE) $(MAKESILENT) -f _deps/whisper-build/src/CMakeFiles/whisper.dir/build.make _deps/whisper-build/src/CMakeFiles/whisper.dir/build
.PHONY : whisper/fast

#=============================================================================
# Target rules for targets named llama

# Build rule for target.
llama: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llama
.PHONY : llama

# fast build rule for target.
llama/fast:
	$(MAKE) $(MAKESILENT) -f _deps/llama-build/src/CMakeFiles/llama.dir/build.make _deps/llama-build/src/CMakeFiles/llama.dir/build
.PHONY : llama/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/Experimental.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/Nightly.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/Continuous.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/NightlyMemoryCheck.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/NightlyStart.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/NightlyUpdate.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/NightlyConfigure.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/NightlyBuild.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/NightlyTest.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/NightlyCoverage.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/NightlyMemCheck.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/NightlySubmit.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalStart.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalUpdate.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalConfigure.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalBuild.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalTest.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalCoverage.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalMemCheck.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalSubmit.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ContinuousStart.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ContinuousUpdate.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ContinuousConfigure.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ContinuousBuild.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ContinuousTest.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ContinuousCoverage.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ContinuousMemCheck.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/ContinuousSubmit.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named sonic

# Build rule for target.
sonic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sonic
.PHONY : sonic

# fast build rule for target.
sonic/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/sonic.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/sonic.dir/build
.PHONY : sonic/fast

#=============================================================================
# Target rules for targets named data

# Build rule for target.
data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 data
.PHONY : data

# fast build rule for target.
data/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/CMakeFiles/data.dir/build.make _deps/espeak-ng-proj-build/CMakeFiles/data.dir/build
.PHONY : data/fast

#=============================================================================
# Target rules for targets named espeak-ng-bin

# Build rule for target.
espeak-ng-bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 espeak-ng-bin
.PHONY : espeak-ng-bin

# fast build rule for target.
espeak-ng-bin/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/src/CMakeFiles/espeak-ng-bin.dir/build.make _deps/espeak-ng-proj-build/src/CMakeFiles/espeak-ng-bin.dir/build
.PHONY : espeak-ng-bin/fast

#=============================================================================
# Target rules for targets named speak-ng

# Build rule for target.
speak-ng: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 speak-ng
.PHONY : speak-ng

# fast build rule for target.
speak-ng/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/src/CMakeFiles/speak-ng.dir/build.make _deps/espeak-ng-proj-build/src/CMakeFiles/speak-ng.dir/build
.PHONY : speak-ng/fast

#=============================================================================
# Target rules for targets named ucd

# Build rule for target.
ucd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ucd
.PHONY : ucd

# fast build rule for target.
ucd/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/src/ucd-tools/CMakeFiles/ucd.dir/build.make _deps/espeak-ng-proj-build/src/ucd-tools/CMakeFiles/ucd.dir/build
.PHONY : ucd/fast

#=============================================================================
# Target rules for targets named speechPlayer

# Build rule for target.
speechPlayer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 speechPlayer
.PHONY : speechPlayer

# fast build rule for target.
speechPlayer/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/src/speechPlayer/CMakeFiles/speechPlayer.dir/build.make _deps/espeak-ng-proj-build/src/speechPlayer/CMakeFiles/speechPlayer.dir/build
.PHONY : speechPlayer/fast

#=============================================================================
# Target rules for targets named espeak-ng

# Build rule for target.
espeak-ng: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 espeak-ng
.PHONY : espeak-ng

# fast build rule for target.
espeak-ng/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/src/libespeak-ng/CMakeFiles/espeak-ng.dir/build.make _deps/espeak-ng-proj-build/src/libespeak-ng/CMakeFiles/espeak-ng.dir/build
.PHONY : espeak-ng/fast

#=============================================================================
# Target rules for targets named test_api

# Build rule for target.
test_api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_api
.PHONY : test_api

# fast build rule for target.
test_api/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/tests/CMakeFiles/test_api.dir/build.make _deps/espeak-ng-proj-build/tests/CMakeFiles/test_api.dir/build
.PHONY : test_api/fast

#=============================================================================
# Target rules for targets named test_encoding

# Build rule for target.
test_encoding: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_encoding
.PHONY : test_encoding

# fast build rule for target.
test_encoding/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/tests/CMakeFiles/test_encoding.dir/build.make _deps/espeak-ng-proj-build/tests/CMakeFiles/test_encoding.dir/build
.PHONY : test_encoding/fast

#=============================================================================
# Target rules for targets named test_ieee80

# Build rule for target.
test_ieee80: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ieee80
.PHONY : test_ieee80

# fast build rule for target.
test_ieee80/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/tests/CMakeFiles/test_ieee80.dir/build.make _deps/espeak-ng-proj-build/tests/CMakeFiles/test_ieee80.dir/build
.PHONY : test_ieee80/fast

#=============================================================================
# Target rules for targets named test_readclause

# Build rule for target.
test_readclause: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_readclause
.PHONY : test_readclause

# fast build rule for target.
test_readclause/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/tests/CMakeFiles/test_readclause.dir/build.make _deps/espeak-ng-proj-build/tests/CMakeFiles/test_readclause.dir/build
.PHONY : test_readclause/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f _deps/espeak-ng-proj-build/tests/CMakeFiles/tests.dir/build.make _deps/espeak-ng-proj-build/tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

src/espeak_tts.o: src/espeak_tts.cc.o
.PHONY : src/espeak_tts.o

# target to build an object file
src/espeak_tts.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/espeak_tts.cc.o
.PHONY : src/espeak_tts.cc.o

src/espeak_tts.i: src/espeak_tts.cc.i
.PHONY : src/espeak_tts.i

# target to preprocess a source file
src/espeak_tts.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/espeak_tts.cc.i
.PHONY : src/espeak_tts.cc.i

src/espeak_tts.s: src/espeak_tts.cc.s
.PHONY : src/espeak_tts.s

# target to generate assembly for a file
src/espeak_tts.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/espeak_tts.cc.s
.PHONY : src/espeak_tts.cc.s

src/llama_device_base.o: src/llama_device_base.cc.o
.PHONY : src/llama_device_base.o

# target to build an object file
src/llama_device_base.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/llama_device_base.cc.o
.PHONY : src/llama_device_base.cc.o

src/llama_device_base.i: src/llama_device_base.cc.i
.PHONY : src/llama_device_base.i

# target to preprocess a source file
src/llama_device_base.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/llama_device_base.cc.i
.PHONY : src/llama_device_base.cc.i

src/llama_device_base.s: src/llama_device_base.cc.s
.PHONY : src/llama_device_base.s

# target to generate assembly for a file
src/llama_device_base.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/llama_device_base.cc.s
.PHONY : src/llama_device_base.cc.s

src/whillats.o: src/whillats.cc.o
.PHONY : src/whillats.o

# target to build an object file
src/whillats.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whillats.cc.o
.PHONY : src/whillats.cc.o

src/whillats.i: src/whillats.cc.i
.PHONY : src/whillats.i

# target to preprocess a source file
src/whillats.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whillats.cc.i
.PHONY : src/whillats.cc.i

src/whillats.s: src/whillats.cc.s
.PHONY : src/whillats.s

# target to generate assembly for a file
src/whillats.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whillats.cc.s
.PHONY : src/whillats.cc.s

src/whillats_osx.o: src/whillats_osx.mm.o
.PHONY : src/whillats_osx.o

# target to build an object file
src/whillats_osx.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whillats_osx.mm.o
.PHONY : src/whillats_osx.mm.o

src/whillats_osx.i: src/whillats_osx.mm.i
.PHONY : src/whillats_osx.i

# target to preprocess a source file
src/whillats_osx.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whillats_osx.mm.i
.PHONY : src/whillats_osx.mm.i

src/whillats_osx.s: src/whillats_osx.mm.s
.PHONY : src/whillats_osx.s

# target to generate assembly for a file
src/whillats_osx.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whillats_osx.mm.s
.PHONY : src/whillats_osx.mm.s

src/whillats_synth.o: src/whillats_synth.mm.o
.PHONY : src/whillats_synth.o

# target to build an object file
src/whillats_synth.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whillats_synth.mm.o
.PHONY : src/whillats_synth.mm.o

src/whillats_synth.i: src/whillats_synth.mm.i
.PHONY : src/whillats_synth.i

# target to preprocess a source file
src/whillats_synth.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whillats_synth.mm.i
.PHONY : src/whillats_synth.mm.i

src/whillats_synth.s: src/whillats_synth.mm.s
.PHONY : src/whillats_synth.s

# target to generate assembly for a file
src/whillats_synth.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whillats_synth.mm.s
.PHONY : src/whillats_synth.mm.s

src/whillats_utils.o: src/whillats_utils.cc.o
.PHONY : src/whillats_utils.o

# target to build an object file
src/whillats_utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whillats_utils.cc.o
.PHONY : src/whillats_utils.cc.o

src/whillats_utils.i: src/whillats_utils.cc.i
.PHONY : src/whillats_utils.i

# target to preprocess a source file
src/whillats_utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whillats_utils.cc.i
.PHONY : src/whillats_utils.cc.i

src/whillats_utils.s: src/whillats_utils.cc.s
.PHONY : src/whillats_utils.s

# target to generate assembly for a file
src/whillats_utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whillats_utils.cc.s
.PHONY : src/whillats_utils.cc.s

src/whisper_transcription.o: src/whisper_transcription.cc.o
.PHONY : src/whisper_transcription.o

# target to build an object file
src/whisper_transcription.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whisper_transcription.cc.o
.PHONY : src/whisper_transcription.cc.o

src/whisper_transcription.i: src/whisper_transcription.cc.i
.PHONY : src/whisper_transcription.i

# target to preprocess a source file
src/whisper_transcription.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whisper_transcription.cc.i
.PHONY : src/whisper_transcription.cc.i

src/whisper_transcription.s: src/whisper_transcription.cc.s
.PHONY : src/whisper_transcription.s

# target to generate assembly for a file
src/whisper_transcription.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/whillats.dir/build.make CMakeFiles/whillats.dir/src/whisper_transcription.cc.s
.PHONY : src/whisper_transcription.cc.s

test/test_utils.o: test/test_utils.cc.o
.PHONY : test/test_utils.o

# target to build an object file
test/test_utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_whillats.dir/build.make CMakeFiles/test_whillats.dir/test/test_utils.cc.o
.PHONY : test/test_utils.cc.o

test/test_utils.i: test/test_utils.cc.i
.PHONY : test/test_utils.i

# target to preprocess a source file
test/test_utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_whillats.dir/build.make CMakeFiles/test_whillats.dir/test/test_utils.cc.i
.PHONY : test/test_utils.cc.i

test/test_utils.s: test/test_utils.cc.s
.PHONY : test/test_utils.s

# target to generate assembly for a file
test/test_utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_whillats.dir/build.make CMakeFiles/test_whillats.dir/test/test_utils.cc.s
.PHONY : test/test_utils.cc.s

test/test_whillats.o: test/test_whillats.cc.o
.PHONY : test/test_whillats.o

# target to build an object file
test/test_whillats.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_whillats.dir/build.make CMakeFiles/test_whillats.dir/test/test_whillats.cc.o
.PHONY : test/test_whillats.cc.o

test/test_whillats.i: test/test_whillats.cc.i
.PHONY : test/test_whillats.i

# target to preprocess a source file
test/test_whillats.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_whillats.dir/build.make CMakeFiles/test_whillats.dir/test/test_whillats.cc.i
.PHONY : test/test_whillats.cc.i

test/test_whillats.s: test/test_whillats.cc.s
.PHONY : test/test_whillats.s

# target to generate assembly for a file
test/test_whillats.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_whillats.dir/build.make CMakeFiles/test_whillats.dir/test/test_whillats.cc.s
.PHONY : test/test_whillats.cc.s

third_party/llama.cpp/examples/llava/clip.o: third_party/llama.cpp/examples/llava/clip.cpp.o
.PHONY : third_party/llama.cpp/examples/llava/clip.o

# target to build an object file
third_party/llama.cpp/examples/llava/clip.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llava.dir/build.make CMakeFiles/llava.dir/third_party/llama.cpp/examples/llava/clip.cpp.o
.PHONY : third_party/llama.cpp/examples/llava/clip.cpp.o

third_party/llama.cpp/examples/llava/clip.i: third_party/llama.cpp/examples/llava/clip.cpp.i
.PHONY : third_party/llama.cpp/examples/llava/clip.i

# target to preprocess a source file
third_party/llama.cpp/examples/llava/clip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llava.dir/build.make CMakeFiles/llava.dir/third_party/llama.cpp/examples/llava/clip.cpp.i
.PHONY : third_party/llama.cpp/examples/llava/clip.cpp.i

third_party/llama.cpp/examples/llava/clip.s: third_party/llama.cpp/examples/llava/clip.cpp.s
.PHONY : third_party/llama.cpp/examples/llava/clip.s

# target to generate assembly for a file
third_party/llama.cpp/examples/llava/clip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llava.dir/build.make CMakeFiles/llava.dir/third_party/llama.cpp/examples/llava/clip.cpp.s
.PHONY : third_party/llama.cpp/examples/llava/clip.cpp.s

third_party/llama.cpp/examples/llava/llava.o: third_party/llama.cpp/examples/llava/llava.cpp.o
.PHONY : third_party/llama.cpp/examples/llava/llava.o

# target to build an object file
third_party/llama.cpp/examples/llava/llava.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llava.dir/build.make CMakeFiles/llava.dir/third_party/llama.cpp/examples/llava/llava.cpp.o
.PHONY : third_party/llama.cpp/examples/llava/llava.cpp.o

third_party/llama.cpp/examples/llava/llava.i: third_party/llama.cpp/examples/llava/llava.cpp.i
.PHONY : third_party/llama.cpp/examples/llava/llava.i

# target to preprocess a source file
third_party/llama.cpp/examples/llava/llava.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llava.dir/build.make CMakeFiles/llava.dir/third_party/llama.cpp/examples/llava/llava.cpp.i
.PHONY : third_party/llama.cpp/examples/llava/llava.cpp.i

third_party/llama.cpp/examples/llava/llava.s: third_party/llama.cpp/examples/llava/llava.cpp.s
.PHONY : third_party/llama.cpp/examples/llava/llava.s

# target to generate assembly for a file
third_party/llama.cpp/examples/llava/llava.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llava.dir/build.make CMakeFiles/llava.dir/third_party/llama.cpp/examples/llava/llava.cpp.s
.PHONY : third_party/llama.cpp/examples/llava/llava.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... copy_espeak_data"
	@echo "... data"
	@echo "... pcaudiolib_external"
	@echo "... speak-ng"
	@echo "... tests"
	@echo "... espeak-ng"
	@echo "... espeak-ng-bin"
	@echo "... ggml"
	@echo "... ggml-base"
	@echo "... ggml-blas"
	@echo "... ggml-cpu"
	@echo "... ggml-metal"
	@echo "... llama"
	@echo "... llava"
	@echo "... llava_shared"
	@echo "... sonic"
	@echo "... speechPlayer"
	@echo "... test_api"
	@echo "... test_encoding"
	@echo "... test_ieee80"
	@echo "... test_readclause"
	@echo "... test_whillats"
	@echo "... ucd"
	@echo "... whillats"
	@echo "... whisper"
	@echo "... src/espeak_tts.o"
	@echo "... src/espeak_tts.i"
	@echo "... src/espeak_tts.s"
	@echo "... src/llama_device_base.o"
	@echo "... src/llama_device_base.i"
	@echo "... src/llama_device_base.s"
	@echo "... src/whillats.o"
	@echo "... src/whillats.i"
	@echo "... src/whillats.s"
	@echo "... src/whillats_osx.o"
	@echo "... src/whillats_osx.i"
	@echo "... src/whillats_osx.s"
	@echo "... src/whillats_synth.o"
	@echo "... src/whillats_synth.i"
	@echo "... src/whillats_synth.s"
	@echo "... src/whillats_utils.o"
	@echo "... src/whillats_utils.i"
	@echo "... src/whillats_utils.s"
	@echo "... src/whisper_transcription.o"
	@echo "... src/whisper_transcription.i"
	@echo "... src/whisper_transcription.s"
	@echo "... test/test_utils.o"
	@echo "... test/test_utils.i"
	@echo "... test/test_utils.s"
	@echo "... test/test_whillats.o"
	@echo "... test/test_whillats.i"
	@echo "... test/test_whillats.s"
	@echo "... third_party/llama.cpp/examples/llava/clip.o"
	@echo "... third_party/llama.cpp/examples/llava/clip.i"
	@echo "... third_party/llama.cpp/examples/llava/clip.s"
	@echo "... third_party/llama.cpp/examples/llava/llava.o"
	@echo "... third_party/llama.cpp/examples/llava/llava.i"
	@echo "... third_party/llama.cpp/examples/llava/llava.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

